DELIMITER $$ -- CAMBIANDO EL DELIMITADOR POR "$$"
DROP PROCEDURE IF EXISTS SP_LIST_USUARIOS $$
CREATE PROCEDURE SP_LIST_USUARIOS() -- NO TENEMOS DATOS DE ENTRADA
BEGIN
	SELECT *
	FROM usuarios_tb;
END$$
DELIMITER ; -- EL DELIMITADOR VUELVE A SER ";"